version: "3.8"

services:
  api:
    build: ./api
    container_name: markindex_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:15-alpine
    container_name: markindex_postgres
    environment:
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgresql/scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
