version: "3.8"

services:
  api:
    build: ./api
    container_name: markindex_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  postgres:
    build: ./databases/postgresql
    container_name: markindex_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
